lfg/lfg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("user.urls")),
    path('main/', include("main.urls")),
]

lfg/main/urls.py
from django.contrib import admin
from django.urls import path
from .views import ExploreView, CreateGroupView, FindGroupView, JoinGroupView, GroupView

app_name = 'main' 

urlpatterns = [
    path("", ExploreView.as_view(), name="explore"),
    path("create", CreateGroupView.as_view(), name="create_group"),
    path("find", FindGroupView.as_view(), name="find_group"),
    path("join/<int:group_id>", JoinGroupView.as_view(), name="join_group"),
    path("group/<int:group_id>", GroupView.as_view(), name="group")

]

lfg/user/urls.py
from django.contrib import admin
from django.urls import path
from .views import CreateUserView, LoginView, LogoutView

app_name = 'user' 

urlpatterns = [
    path("", CreateUserView.as_view(), name="create_user"),
    path("login/", LoginView.as_view(), name="login_user"),
    path("logout/", LogoutView.as_view(), name="logout_user")
]

lfg/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.conf import settings
from django.db import IntegrityError
from django.core.validators import MaxValueValidator, MinValueValidator


class Tags(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name


class Games(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class MyUserManager(UserManager):
    def create_user(self, email, password, username, **extra_fields):
        if not email and username:
            raise ValueError("The Email and Username must be set")
        elif len(username) > 32:
            raise IntegrityError("username cant be longer than 32 characters")
        email = self.normalize_email(email)
        user = self.model(email=email,
                          username=username,
                          **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user


class User(AbstractUser):
    username = models.CharField(max_length=32, unique=True)
    email = models.EmailField(unique=True)
    tags = models.ManyToManyField(Tags, related_name='user_tags', blank=True)
    games = models.ManyToManyField(Games, related_name='user_games', blank=True)
   
    objects = MyUserManager()
   
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']


class Groups(models.Model):
    name = models.CharField(max_length=255, unique=False)
    members = models.ManyToManyField(User, related_name='user_groups')
    group_size = models.IntegerField(default=6, validators=[MinValueValidator(1), MaxValueValidator(6)])
    is_public = models.BooleanField(default=True)
    game = models.ForeignKey(Games, default=None, null=True, blank=True, on_delete=models.CASCADE) 



class Friends(models.Model):
    from_user = models.ForeignKey(User, related_name='outgoing_friends', on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name='incoming_friends', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = [('from_user', 'to_user')]

lfg/user/models.py
from django.db import models

# Create your models here.

lfg/main/forms.py
from django import forms
from core.models import Groups

class CreateGroupForm(forms.ModelForm):

    class Meta:
        model = Groups
        fields = ("name", "group_size", "is_public", "game")

lfg/user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth import get_user_model

class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField(label="Email", required=True)
    class Meta:
        model = get_user_model()
        fields = ("username", "email")

lfg/core/views.py
from django.shortcuts import render

# Create your views here.

lfg/main/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from core.models import Games, Groups
from .forms import CreateGroupForm
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin


class ExploreView(LoginRequiredMixin, View):
    def get(self, request):
        games = Games.objects.all()
        return render(request, "main/explore.html", {"games": games})
    def post(self, request):
        pass


class CreateGroupView(LoginRequiredMixin, View):
    def get(self, request):
        form = CreateGroupForm()
        return render(request, "main/create_group.html", {"form": form})

    def post(self, request):
        form = CreateGroupForm(request.POST)
        if form.is_valid():
            group = form.save(commit=False)
            group.save()
            user = request.user  
            group.members.add(user)
            return redirect("main:explore")
        return render(request, "main/create_group.html", {"form": form})
    

class FindGroupView(LoginRequiredMixin, View):
    def get(self, request):
        groups = Groups.objects.all()
        return render(request, "main/find_group.html", {"groups": groups})


class JoinGroupView(LoginRequiredMixin, View):
    def get(self, request, group_id):
        try: 
            group = Groups.objects.get(pk=group_id)
            print(group.members.all())
            print(request.user)
            if group is not None and request.user not in group.members.all():
                try:
                    groups = Groups.objects.filter(members=request.user)
                    if len(groups) == 0:
                        group.members.add(request.user)
                except Groups.DoesNotExist:
                    group.members.add(request.user)
                
                
            return redirect("main:find_group")
        except Groups.DoesNotExist:
            return redirect("main:find_group")
    

class GroupView(LoginRequiredMixin, View):
    def get(self, request, group_id):
        group = Groups.objects.get(pk=group_id)
        if group is not None and request.user in group.members.all():
            return render(request, "main/group.html", {"group": group})
        return redirect("main:find_group")
    

lfg/user/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from .forms import MyUserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.

class LoginView(View):
    def get(self, request):
        form = AuthenticationForm()
        return render(request, "user/login.html", {"form": form})
    
    def post(self, request):
        print(request.user)
        if request.user.is_authenticated:
            return redirect("main:find_group")
        form = AuthenticationForm(None, data=request.POST)
        if form.is_valid():
            print("valid")
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            print(user)
            if user is not None:
                login(request, user)
                # Redirect to success URL (e.g., protected view)
                return redirect("main:find_group")
            else:
                # Handle invalid login attempt (e.g., display error message)
                form.add_error(None, 'Invalid username or password')
        else:
            # Handle form validation errors
            print("Form validation errors:")  # Optional for debugging
            for error in form.errors:
                print(error)  # Optional for debugging

        return render(request, "user/login.html", {"form": form})


class CreateUserView(View):
    
    def get(self, request):
        form = MyUserCreationForm()
        return render(request, "user/register.html", {"form": form})

    def post(self, request):
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("user:login_user")
        return render(request, "user/register.html", {"form": form})

class LogoutView(View):
    def get(self, request):
        logout(request) 
        return redirect('user:login_user') 

lfg/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
     
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        {% block scripts %}

        {% endblock %}
        
        <link rel="stylesheet" href="{% static "core/base.css" %}">
        {% block head %}
        
        {% endblock %}
    </head>
    <body >
        <img class="desktop-img" src="{% static 'core/desktop.png' %}" alt="My Image">
        <img class="headset-img" src="{% static 'core/headset.png' %}" alt="My Image">
        <nav class="navbar navbar-expand-lg  navbar-custom">

            <div class="container-fluid">
              <a class="navbar-brand" href="#">LFG</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dropdown
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                  </li>
                </ul>
                <form class="d-flex" role="search">
                  <input class="navbar-search form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
        </nav>
        <div class="gradient-box"></div>
        {% block body %}
        
        {% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>    
    </body>
   </html>

lfg/main/templates/main/create_group.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
</head>
<body>
    <h1>create group</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">create</button>
    </form>
    {% if form.errors %}
        <ul>
            {% for error in form.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <a href="{% url 'user:logout_user' %}"><button>Logout</button></a>
    <a href="{% url 'main:find_group' %}"><button>Find Group</button></a>
    <a href="{% url 'main:explore' %}"><button>explore</button></a>
</body>
</html>

lfg/main/templates/main/explore.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
   
    {% for game in games %}
        <h3>{{game}}</h3>
    {% endfor %}
    <a href="{% url 'user:logout_user' %}"><button>Logout</button></a>
    <a href="{% url 'main:find_group' %}"><button>Find Group</button></a>
    <a href="{% url 'main:create_group' %}"><button>create group</button></a>
   
</body>

</html>

lfg/main/templates/main/find_group.html
<!DOCTYPE html>
<html>
<head>
    <title>Find Groups</title>
</head>
<body>
    <h1>Groups</h1>
    <hr>
    {% for group in groups %}
        <h1>{{ group.pk }}</h1>
        <h2>{{ group.name }}</h2>
        {% for member in group.members.all %}
            {{ member.username }}
        {% endfor %}
        
        <h3>{{ group.game }}</h3>
       
        <button id="{{group.pk}}"  onclick="window.location.href='{% url "main:join_group" group_id=group.pk %}'">JOIN</button>
        <button id="{{group.pk}}"  onclick="window.location.href='{% url "main:group" group_id=group.pk %}'">group</button>
        <hr>
        

    {% endfor %}
    <a href="{% url 'user:logout_user' %}"><button>Logout</button></a>
    <a href="{% url 'main:explore' %}"><button>explore</button></a>
    <a href="{% url 'main:create_group' %}"><button>create group</button></a>
    

</body>
</html>

lfg/main/templates/main/group.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
   
    <h3>{{group.name}}</h3>
    {% for user in group.members.all %}
        {{ user }}
    {% endfor %}
    <h3>{{group.group_size}}</h3>
    <h3>{{group.is_public}}</h3>
    <h3>{{group.game}}</h3>

    <hr>
    
    <a href="{% url 'user:logout_user' %}"><button>Logout</button></a>
    <a href="{% url 'main:find_group' %}"><button>Find Group</button></a>
    <a href="{% url 'main:create_group' %}"><button>create group</button></a>
   
</body>

</html>

lfg/user/templates/user/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
    {% if form.errors %}
        <ul>
            {% for error in form.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</body>
</html>

lfg/user/templates/user/register.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Register{% endblock %}

{% block head %} 
  <link rel="stylesheet" href="{% static "user/register.css" %}">
{% endblock %}

{% block scripts %}


{% endblock %}

{% block body %}

  <div id="title-div" >
      <h3>Register</h3>
  </div>

  <div class="container">
      <div class="" id="register-container">
              <form method="POST">
                  {% csrf_token %}
                  <p>{{ form.username.label }}: {{ form.username }}</p>
                  <p>{{ form.email.label }}: {{ form.email }}</p>
                  <p>{{ form.password1.label }}: {{ form.password1 }}</p>
                  <p>{{ form.password2.label }}: {{ form.password2 }}</p>
                  <div class="d-flex">
                      <button id="register-button" type="submit">Register</button> 
                      <a href="{% url 'user:login_user' %}"><button id="login-button">Login</button></a>  
                  </div>
              </form> 
      </div>


  </div>

{% endblock %}